#!/usr/bin/env bash

sudo confirm ':: Update official packages?' &&
await ping -nc1 8.8.8.8 &> /dev/null &&
sudo aura -Suy &&
confirm ':: Update AUR packages?' &&
sudo aura -Akua;
confirm ':: Remove unused packages and repositories?' &&
sudo aura -Sc;
while true; do confirm ':: Confirm exit.' && exit 1; done
