#!/usr/bin/env bash

while true; do
	[ -z "$@" ] || echo -n "$@ "
	read -p "(Y/n): " -n 1 -r
	echo
	[[ $REPLY =~ ^[Yy]$ ]] && exit 0
	[[ $REPLY =~ ^[Nn]$ ]] && exit 1
	echo "Please enter 'Y' or 'N'"
done
	
