#!/usr/bin/env bash
if [ -z $1 ]; then
	echo No process name specified.
	exit 1;
fi
pid=$(pidof $1)
if [ $? -gt 0 ]; then
	echo Process $1 not found.
	exit 1;
fi
while [ 1 ]; do
	output=$(pmap $pid)
	if [ $? -gt 0 ]; then exit; fi
	echo $output | grep 'total' | sed 's/.* \([0-9]*\)K.*/\1/'
	sleep 1s
done
