#!/usr/bin/env bash
if [ -z $1 ]; then
	echo No process name specified.
	exit 1;
fi
proc=$1

find_process() {
	while [ 1 ]; do
		local proc=$1
		pid=$(pidof -s $proc)
		if [ $? -eq 0 ]; then return; fi
		sleep 0.5s
	done
}

log_process() {
	while [ 1 ]; do
		local output=$(pmap $pid)
		if [ -z "$output" ]; then return; fi
		echo "$output" | grep 'total' | sed 's/.* \([0-9]*\)K.*/\1/'
		sleep 1s
	done
}

while [ 1 ]; do
	find_process $proc
	log_process
done