#!/usr/bin/env bash

events+='-e close_write '
events+='-e delete '
events+='-e moved_to '

exclude=".*(\.sw[xp]x?|~|4913)$"

timefmt='%x %X'

format='Event(s) %e on "%w%f" at %T'

clear
while true; do
	output=$(inotifywait -qr $events \
			--exclude="$exclude" \
			--format="$format" \
			--timefmt="$timefmt" .) || exit $?
	clear
	echo $output
	$@
done
