#!/usr/bin/env bash

events+='-e close_write '
events+='-e delete '
events+='-e move '

exclude=".*(sw[xp]|~|4913)$"

clear
while true; do
	output=$(inotifywait -qr $events --exclude="$exclude" .) || exit $?
	clear
	echo $output
	$@
done
